apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev1-pvc
  namespace: default
spec:
  storageClassName: dev1-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi